all:
  hosts:
    web1:
      ansible_host: 10.0.0.10
    web2:
      ansible_host: 10.0.1.10
    prometheus:
      ansible_host: 10.0.0.20
    grafana:
      ansible_host: 192.168.0.30
    elasticsearch:
      ansible_host: 10.0.0.40
    kibana:
      ansible_host: 192.168.0.50
    bastion:
      ansible_host: 192.168.0.100